version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_toolbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_admin.sql:/docker-entrypoint-initdb.d/init_admin.sql
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_toolbox
      POSTGRES_HOST: db
      SECRET_KEY: your-secret-key-here
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  zap:
    image: owasp/zap2docker-stable
    volumes:
      - ./zap-data:/zap/wrk
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    driver: bridge 